## Loan Prediction Project – Insights
### Data Pre Processing + Data Analysis:
#### Objective
To automate loan eligibility prediction based on customer details such as income, credit history, loan amount, and other features.

### Dataset Overview
The dataset contains applicant demographic and financial details including income, loan amount, credit history, and property area to determine loan approval status.

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("C:\\Python Projects\\Github Portfolio\\1. Loan Prediction Project\\LoanData.csv")
print(df)

      Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No
1    LP001003    Male     Yes          1      Graduate            No
2    LP001005    Male     Yes          0      Graduate           Yes
3    LP001006    Male     Yes          0  Not Graduate            No
4    LP001008    Male      No          0      Graduate            No
..        ...     ...     ...        ...           ...           ...
609  LP002978  Female      No          0      Graduate            No
610  LP002979    Male     Yes         3+      Graduate            No
611  LP002983    Male     Yes          1      Graduate            No
612  LP002984    Male     Yes          2      Graduate            No
613  LP002990  Female      No          0      Graduate           Yes

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0         NaN             360.0
1               4583             1508.0       128.0             360.0
2               3000                0.0        66.0             360.0
3               2583             2358.0       120.0             360.0
4               6000                0.0       141.0             360.0
..               ...                ...         ...               ...
609             2900                0.0        71.0             360.0
610             4106                0.0        40.0             180.0
611             8072              240.0       253.0             360.0
612             7583                0.0       187.0             360.0
613             4583                0.0       133.0             360.0

     Credit_History Property_Area Loan_Status
0               1.0         Urban           Y
1               1.0         Rural           N
2               1.0         Urban           Y
3               1.0         Urban           Y
4               1.0         Urban           Y
..              ...           ...         ...
609             1.0         Rural           Y
610             1.0         Rural           Y
611             1.0         Urban           Y
612             1.0         Urban           Y
613             0.0     Semiurban           N

[614 rows x 13 columns]

### 2. To know about the data in a table:

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             601 non-null    object
 2   Married            611 non-null    object
 3   Dependents         599 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      582 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

#### note:
- Here, we can understand that Gender, Married, Education, Self_Employed, Property Area and Loan Status are text data which are nothing but a CATEGORICAL column data. 
- Loan Status is Target variable. Loan_ID is the unique ID column / Identifier.

In [3]:
df.shape

(614, 13)

In [4]:
df.dtypes

Loan_ID               object
Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
Loan_Status           object
dtype: object

In [5]:
df['Loan_ID'].nunique()

614

#### Always perform unique() for each column to check the values of each column

## 3. Finding Missing Values:

In [6]:
df.isnull()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,False,False,False,False,False,False,False,False,True,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,False,False,False,False,False,False,False,False,False,False,False,False,False
610,False,False,False,False,False,False,False,False,False,False,False,False,False
611,False,False,False,False,False,False,False,False,False,False,False,False,False
612,False,False,False,False,False,False,False,False,False,False,False,False,False
613,False,False,False,False,False,False,False,False,False,False,False,False,False

In [7]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

Here it shows that, there are few missing values in few of the columns

In [8]:
df.isnull().sum()/len(df)*100

Loan_ID              0.000000
Gender               2.117264
Married              0.488599
Dependents           2.442997
Education            0.000000
Self_Employed        5.211726
ApplicantIncome      0.000000
CoapplicantIncome    0.000000
LoanAmount           3.583062
Loan_Amount_Term     2.280130
Credit_History       8.143322
Property_Area        0.000000
Loan_Status          0.000000
dtype: float64

Here it gives the percentage of the missing values in each of the column.

##### From the missing values, we can understand that: 
##### -Gender, Married, Dependents, LoanAmount, Loan_amouont_term has low % of missing values and they are safe to fix.
##### -Self_Employed has medium % missing values and is slightly higher but still manageable.
##### -Credit_History has highest % of missing values and is critical.

##### | Column           | Missing % | Category | Action                     |
##### | Gender           | 2.1%      | Low      | Fill mode                  |
##### | Married          | 0.4%      | Low      | Fill mode                  |
##### | Dependents       | 2.4%      | Low      | Fill mode                  |
##### | LoanAmount       | 3.5%      | Low      | Fill median                |
##### | Loan_Amount_Term | 2.2%      | Low      | Fill median                |
##### | Self_Employed    | 5.2%      | Medium   | Fill mode                  |
##### | Credit_History   | 8.1%      | Medium   | Fill mode (VERY important) |

### 4. Data Cleaning
- Here, one more thing is, Loan_ID is NOT a categorical feature for modeling.
- Even though it is “text”, it is an Identifier column (ID column) and has no predictive meaning.
#### > Why do we drop Loan_ID?
- Because, It is unique for every row, Machine learning learns patterns and IDs create noise, not patterns.
- ALWAYS DROP THE IDENTIFIERS FIRST.

In [9]:
df. drop('Loan_ID', axis=1, inplace = True)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Gender             601 non-null    object
 1   Married            611 non-null    object
 2   Dependents         599 non-null    object
 3   Education          614 non-null    object
 4   Self_Employed      582 non-null    object
 5   ApplicantIncome    614 non-null    int64
 6   CoapplicantIncome  614 non-null    float64
 7   LoanAmount         592 non-null    float64
 8   Loan_Amount_Term   600 non-null    float64
 9   Credit_History     564 non-null    float64
 10  Property_Area      614 non-null    object
 11  Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(7)
memory usage: 57.7+ KB

In [11]:
df.isnull().sum()

Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

### 4.1 Missing Value Treatment
### 4.1.1. Replacing Categorical Data Missing Values with mode

- Here now if we observe, we can see that, self_ employed column has highest missing values of 32.
- since it is an important column and is a categorical column, we need to use the

In [12]:
#To replace the missing values in Self_ employed column, we do:
df['Self_Employed'] = df['Self_Employed'].fillna(df['Self_Employed'].mode()[0])

In [13]:
df.isnull().sum()

Gender               13
Married               3
Dependents           15
Education             0
Self_Employed         0
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [14]:
df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])

In [15]:
df['Dependents'] = df['Dependents'].fillna(df['Dependents'].mode()[0])

In [16]:
df['Married'] = df['Married'].fillna(df['Married'].mode()[0])

In [17]:
df['Credit_History'] = df['Credit_History'].fillna(df['Credit_History'].mode()[0])

In [18]:
df.isnull().sum()

Gender                0
Married               0
Dependents            0
Education             0
Self_Employed         0
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History        0
Property_Area         0
Loan_Status           0
dtype: int64

### 4.1.2. Replacing Numerical Data Missing Values with median

In [19]:
df['LoanAmount'] = df['LoanAmount'].fillna(df['LoanAmount'].median())

In [20]:
df['Loan_Amount_Term'] = df['Loan_Amount_Term'].fillna(df['Loan_Amount_Term'].median())

In [21]:
df.isnull().sum()

Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

### 5. Feature Engineering

#### Feature 1: Total Income

In [22]:
df['Total_Income'] = df['ApplicantIncome']+ df['CoapplicantIncome']
df

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,Total_Income
0,Male,No,0,Graduate,No,5849,0.0,128.0,360.0,1.0,Urban,Y,5849.0
1,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N,6091.0
2,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y,3000.0
3,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y,4941.0
4,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y,6000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y,2900.0
610,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y,4106.0
611,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y,8312.0
612,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y,7583.0
613,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N,4583.0

#### Feature 2: Loan Burden

In [23]:
df['Loan_to_Income'] = df['LoanAmount']/df['Total_Income']
df

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,Total_Income,Loan_to_Income
0,Male,No,0,Graduate,No,5849,0.0,128.0,360.0,1.0,Urban,Y,5849.0,0.021884
1,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N,6091.0,0.021015
2,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y,3000.0,0.022000
3,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y,4941.0,0.024287
4,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y,6000.0,0.023500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y,2900.0,0.024483
610,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y,4106.0,0.009742
611,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y,8312.0,0.030438
612,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y,7583.0,0.024660
613,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N,4583.0,0.029020

In [24]:
df.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,Total_Income,Loan_to_Income
0,Male,No,0,Graduate,No,5849,0.0,128.0,360.0,1.0,Urban,Y,5849.0,0.021884
1,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N,6091.0,0.021015
2,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y,3000.0,0.022000
3,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y,4941.0,0.024287
4,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y,6000.0,0.023500

### 6. Data Preprocessing

#### 6.1 For Binary Columns:

##### 6.1. Encoding
Machines cannot understand text, so convering the columns which has binary values to only numbers

In [25]:
df['Gender'] = df['Gender'].map({'Male':1, 'Female':0})

df['Married'] = df['Married'].map({'Yes':1, 'No':0})

df['Self_Employed'] = df['Self_Employed'].map({'Yes':1, 'No':0})

df['Education'] = df['Education'].map({'Graduate':1, 'Not Graduate':0})

df['Loan_Status'] = df['Loan_Status'].map({'Y':1, 'N':0})

In [26]:
df['Dependents'] = df['Dependents'].replace('3+', 3)
df['Dependents'] = df['Dependents'].astype(int)

In [27]:
df['Property_Area'] = df['Property_Area'].map({
    'Rural':0,
    'Semiurban':1,
    'Urban':2
})

In [28]:
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Gender             614 non-null    int64
 1   Married            614 non-null    int64
 2   Dependents         614 non-null    int64
 3   Education          614 non-null    int64
 4   Self_Employed      614 non-null    int64
 5   ApplicantIncome    614 non-null    int64
 6   CoapplicantIncome  614 non-null    float64
 7   LoanAmount         614 non-null    float64
 8   Loan_Amount_Term   614 non-null    float64
 9   Credit_History     614 non-null    float64
 10  Property_Area      614 non-null    int64
 11  Loan_Status        614 non-null    int64
 12  Total_Income       614 non-null    float64
 13  Loan_to_Income     614 non-null    float64
dtypes: float64(6), int64(8)
memory usage: 67.3 KB

In [29]:
df['Credit_History'] = df['Credit_History'].astype(int)

#### 6.2 For Categorical Columns

#### 6.2.1 Separate Features & Target

##### We are doing this because the Model needs:
##### x = Input Information
##### y = What we want to predict
##### As the Target Column is 'Loan_Status',so lets drop that column.It contains the answers that the model should learn.

In [38]:
X = df.drop('Loan_Status', axis = 1)

In [36]:
y = df["Loan_Status"]

#### 6.2.2 Remove Unnecessary Columns

##### Note: Since, Loan_ID is just an identifier. It doesn't help the model predict loan approval.

In [ ]:
X = X.drop('Loan_ID', axis = 1)

In [33]:
df.columns

Index(['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed',
       'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status',
       'Total_Income', 'Loan_to_Income'],
      dtype='object')

In [35]:
y = df["Loan_Status"]

In [40]:
X.columns

Index(['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed',
       'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Total_Income',
       'Loan_to_Income'],
      dtype='object')

In [42]:
X.select_dtypes(include = 'object').columns

Index([], dtype='object')

In [43]:
X.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Total_Income,Loan_to_Income
0,1,0,0,1,0,5849,0.0,128.0,360.0,1,2,5849.0,0.021884
1,1,1,1,1,0,4583,1508.0,128.0,360.0,1,0,6091.0,0.021015
2,1,1,0,1,1,3000,0.0,66.0,360.0,1,2,3000.0,0.022000
3,1,1,0,0,0,2583,2358.0,120.0,360.0,1,2,4941.0,0.024287
4,1,0,0,1,0,6000,0.0,141.0,360.0,1,2,6000.0,0.023500

In [44]:
X.dtypes

Gender                 int64
Married                int64
Dependents             int64
Education              int64
Self_Employed          int64
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History         int64
Property_Area          int64
Total_Income         float64
Loan_to_Income       float64
dtype: object

#### 6.2.3. Train-Test Split

##### Objective: To divide the dataset into training and testing sets so that the model can learn from training data and evaluate performance on unseen testing data.

In [46]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split( X, 
                                                     y,
                                                     test_size=0.2,
                                                     random_state = 42,
                                                     stratify = y
                                                   )

##### Note: where, 
##### X_train - Features used for training the model
##### X_test - Features used for testing the model
##### y_train - Target values for training
##### y_test - Target values for evaluation
##### test_size = 0.2 = 20% data used for testing
##### random_state = 42 = Gives reproducible results
##### stratify = y = Maintains the same Loan_Status distribution in train and test data. Stratify keeps the same ratio in train and test.

### 6.2.4. Feature Scaling
- We only Scale the Continuous Numerical Features, not encoded Categories.
- Here, we use StandardScaler and it converts to mean = 0, std = 1

In [47]:
from sklearn.preprocessing import StandardScaler

In [48]:
scaler = StandardScaler()

In [49]:
cols_to_scale = [
    'ApplicantIncome',
    'CoapplicantIncome',
    'LoanAmount',
    'Loan_Amount_Term',
    'Total_Income',
    'Loan_to_Income'
]

In [50]:
df[cols_to_scale] = scaler.fit_transform(df[cols_to_scale])

In [51]:
df

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,Total_Income,Loan_to_Income
0,1,0,0,1,0,0.072991,-0.554487,-0.211241,0.273231,1,2,1,-0.182184,-0.229045
1,1,1,1,1,0,-0.134412,-0.038732,-0.211241,0.273231,1,0,0,-0.144684,-0.328983
2,1,1,0,1,1,-0.393747,-0.554487,-0.948996,0.273231,1,2,1,-0.623656,-0.215721
3,1,1,0,0,0,-0.462062,0.251980,-0.306435,0.273231,1,2,1,-0.322885,0.047102
4,1,0,0,1,0,0.097728,-0.554487,-0.056551,0.273231,1,2,1,-0.158785,-0.043308
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,0,0,0,1,0,-0.410130,-0.554487,-0.889500,0.273231,1,0,1,-0.639152,0.069651
610,1,1,3,1,0,-0.212557,-0.554487,-1.258378,-2.522836,1,0,1,-0.452274,-1.624694
611,1,1,1,1,0,0.437174,-0.472404,1.276168,0.273231,1,2,1,0.199475,0.754148
612,1,1,2,1,0,0.357064,-0.554487,0.490816,0.273231,1,2,1,0.086512,0.090073
613,0,0,0,1,1,-0.134412,-0.554487,-0.151745,0.273231,0,1,0,-0.378359,0.591203

##### Features = input = Can be Scaled.
##### Target = output = Never Scale.

### 7. Model Building

#### 7.1 Build Logistic Regression Model

##### Loan Approved
#####   Yes / No. since it is Binary Classification.

In [54]:
df.columns

Index(['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed',
       'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status',
       'Total_Income', 'Loan_to_Income'],
      dtype='object')

In [55]:
df.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,Total_Income,Loan_to_Income
0,1,0,0,1,0,0.072991,-0.554487,-0.211241,0.273231,1,2,1,-0.182184,-0.229045
1,1,1,1,1,0,-0.134412,-0.038732,-0.211241,0.273231,1,0,0,-0.144684,-0.328983
2,1,1,0,1,1,-0.393747,-0.554487,-0.948996,0.273231,1,2,1,-0.623656,-0.215721
3,1,1,0,0,0,-0.462062,0.251980,-0.306435,0.273231,1,2,1,-0.322885,0.047102
4,1,0,0,1,0,0.097728,-0.554487,-0.056551,0.273231,1,2,1,-0.158785,-0.043308

In [ ]:
from sklearn.linear_model import LogisticRegression

In [58]:
log_model = LogisticRegression()

In [59]:
log_model.fit(X_train, y_train)

C:\Users\tejas\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [60]:
y_pred = log_model.predict(X_test)

#### 7.2. Model Evaluation

In [65]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

accuracy = accuracy_score(y_test,y_pred)
accuracy

0.8617886178861789

In [66]:
confusion_matrix(y_test, y_pred)

array([[22, 16],
       [ 1, 84]])

#### True Negative (TN) = 22
##### Actual loan rejected
##### Model predicted rejected
##### Correct predictions
#### False Positive (FP) = 16
##### Actual loan rejected
##### Model predicted approved
##### Wrong predictions
#### False Negative (FN) = 1
##### Actual loan approved
##### Model predicted rejected
##### Wrong predictions
#### True Positive (TP) = 84
##### Actual loan approved
##### Model predicted approved
##### Correct predictions

In [67]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.96      0.58      0.72        38
           1       0.84      0.99      0.91        85

    accuracy                           0.86       123
   macro avg       0.90      0.78      0.81       123
weighted avg       0.88      0.86      0.85       123

- class 0 = Loan Rejected
- class 1 = Loan Approved

- The Logistic Regression model achieved an accuracy of 86% on the test dataset.

- The confusion matrix shows that the model correctly predicted 84 approved loans and 22 rejected loans.

- The model performed well in identifying approved loans with a recall of 99%, meaning it successfully captured most eligible applicants.

- However, the recall for rejected loans was 58%, indicating that some rejected applications were incorrectly classified as approved.

- Overall, Logistic Regression provided a good baseline model for loan approval prediction.

## Key Insights

* Credit History is one of the most influential factors in determining loan approval decisions, as it reflects the applicant's repayment reliability.

* Combining Applicant Income and Co-applicant Income provides a better understanding of the applicant's overall financial strength.

* The Loan-to-Income ratio helps measure the applicant's loan burden and repayment capability.

* Missing values were treated appropriately based on the nature of the data, using suitable techniques for categorical and numerical features.

* Feature scaling was applied to standardize numerical features, which helps optimization-based algorithms such as Logistic Regression perform better.

* Removing irrelevant features, such as Loan_ID, reduces unnecessary noise and helps the model learn meaningful patterns.

* Logistic Regression achieved good performance with 86% accuracy, showing that the selected features provide useful information for predicting loan approval status.